import Head from "next/head";
import DefaultLayout from "../layouts";
//import Image from "next/image";
import styles from "../styles/Home.module.css";
import { RichText } from "prismic-reactjs";
import { linkResolver } from "../prismic-configuration";

import SliceZone from "../components/slices/SliceZone";
import { Client } from "../utils/prismicHelpers";

export default function Home(props) {
  const { data } = props.doc;
  console.log("props", props);
  return (
    <DefaultLayout>
      <div className={styles.container}>
        <Head>
          <title>Landing Page</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <div>
            {RichText.asText(data.header_text)}
            <RichText render={data.header_text} linkResolver={linkResolver}/>
          </div>
          <h1>{data.page_title[0].text}</h1>
          {data.page_content && <SliceZone sliceZone={data.page_content} />}
        </main>

        <footer className={styles.footer}>Footer</footer>
      </div>
    </DefaultLayout>
  );
}

export async function getStaticProps({ preview = null, previewData = {} }) {
  const { ref } = previewData;

  const client = Client();

  const doc =
    (await client.getSingle("landing_page", ref ? { ref } : null)) || {};
  //const menu = await client.getSingle('menu', ref ? { ref } : null) || {}

  return {
    props: {
      doc,
      //menu,
      preview,
    },
  };
}
